// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOuH7zQ_8NsUWldeZ7wNSnPGALbILCl3Q',
    appId: '1:3783311909:web:bee9de5764569b03a9f5cc',
    messagingSenderId: '3783311909',
    projectId: 'chordflow2',
    authDomain: 'chordflow2.firebaseapp.com',
    storageBucket: 'chordflow2.firebasestorage.app',
    measurementId: 'G-8C28NY0MMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-UEHGtfKFt_osbWVGofesGvebX5QZiI',
    appId: '1:3783311909:android:9b6f91e402b71424a9f5cc',
    messagingSenderId: '3783311909',
    projectId: 'chordflow2',
    storageBucket: 'chordflow2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChwsaM_KQb6YNIKstgx10758DoqmfXgZs',
    appId: '1:3783311909:ios:34336adf5f051f20a9f5cc',
    messagingSenderId: '3783311909',
    projectId: 'chordflow2',
    storageBucket: 'chordflow2.firebasestorage.app',
    iosBundleId: 'com.example.chordflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChwsaM_KQb6YNIKstgx10758DoqmfXgZs',
    appId: '1:3783311909:ios:34336adf5f051f20a9f5cc',
    messagingSenderId: '3783311909',
    projectId: 'chordflow2',
    storageBucket: 'chordflow2.firebasestorage.app',
    iosBundleId: 'com.example.chordflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOuH7zQ_8NsUWldeZ7wNSnPGALbILCl3Q',
    appId: '1:3783311909:web:bdd2ff9c74ba86c2a9f5cc',
    messagingSenderId: '3783311909',
    projectId: 'chordflow2',
    authDomain: 'chordflow2.firebaseapp.com',
    storageBucket: 'chordflow2.firebasestorage.app',
    measurementId: 'G-LWHXVXJ4DF',
  );
}
